- name: Crear carpeta performance
  file: path=/home/linux/performance state=directory owner={{ hostvars['manager01']['ansible_ssh_user'] }} group={{ hostvars['manager01']['ansible_ssh_user'] }}

- name: Copiar archivo yaml de servicios
  template: src=jmeter-stack-compose.yml.j2 dest=/home/linux/performance/jmeter-stack-compose.yml owner={{ hostvars['manager01']['ansible_ssh_user'] }} group={{ hostvars['manager01']['ansible_ssh_user'] }}

- name: Ejecutar servicios del stack de Jmeter
  shell: docker stack deploy -c ./performance/jmeter-stack-compose.yml jmeter-stack
