# Performance Framework
version: "3.7"
services:
  master:
    image: "joabgonzalez/jmt-master"
    hostname: "jmeter-master"
    # stdin_open: true
    # tty: true
    environment:
      GIT: "https://joabtsoft@bitbucket.org/joabtsoft/hites-cyber.git"
    volumes:
      - "jmeter-results:/jmeter/apache-jmeter/bin/results"
    networks:
      - "performance"
    # deploy:
    #   placement:
    #     constraints:
    #       - "node.role == manager"
    #   resources:
    #     limits:
    #       cpus: "1.5"
    #       memory: "3072M"
    #     reservations:
    #       cpus: "1.5"
    #       memory: "3072M"
  slave:
    image: "joabgonzalez/jmts:hites"
    hostname: "jmeter-slave"
    depends_on:
      - "master"
    environment:
      GIT: "https://joabtsoft@bitbucket.org/joabtsoft/hites-cyber.git"
    networks:
      - "performance"
    # deploy:
    #   replicas: 25
    #   placement:
    #     constraints:
    #       - "node.role == worker"
    #   resources:
    #     limits:
    #       cpus: "1.5"
    #       memory: "3072M"
    #     reservations:
    #       cpus: "1.5"
    #       memory: "3072M"
  # redis:
  #   image: "redis"
  #   hostname: "redis"
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - "performance"
  #   deploy:
  #     placement:
  #       constraints:
  #         - "node.role == manager"
  influxdb:
    image: "influxdb"
    hostname: "influxdb"
    ports:
      - "8086:8086"
    environment:
      - "INFLUXDB_DB=performance"
      - "INFLUXDB_USER=performance"
      - "INFLUXDB_USER_PASSWORD=performance"
    volumes:
      - "jmeter-influxdb:/var/lib/influxdb"
    networks:
      - "performance"
    # deploy:
    #   placement:
    #     constraints:
    #       - "node.role == manager"
  grafana:
    image: "grafana/grafana"
    hostname: "grafana"
    depends_on:
      - "influxdb"
    ports:
      - "80:3000"
    volumes:
      - "jmeter-grafana:/var/lib/grafana"
    networks:
      - "performance"
    # deploy:
    #   placement:
    #     constraints:
    #       - "node.role == manager"
  # telegraf:
  #   image: "joabgonzalez/telegraf"
  #   hostname: "telegraf-{{.Task.Slot}}"
  #   environment:
  #     INFLUXDB_HOST: "influxdb"
  #   depends_on:
  #     - "influxdb"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #     - "/var/lib/docker/volumes:/var/lib/docker/volumes"
  #   networks:
  #     - "performance"
  #   deploy:
  #     mode: global
  #     resources:
  #       limits:
  #         cpus: "0.0625"
  #         memory: "64M"
networks:
  performance:
volumes:
  jmeter-results:
  jmeter-tests:
  jmeter-data:
  jmeter-influxdb:
  jmeter-grafana:
...