- name: Obtener IP de los esclavos
  shell: docker ps -q
  register: contenedores

- name: Obteniendo direccion IP de los esclavos
  shell: docker inspect --format '{''{.Name}''} - {''{range .NetworkSettings.Networks}''}{''{.IPAddress}''}{''{end}''}' {{item}} | grep jmeter-stack_slave | grep -oP "\d+\.\d+\.\d+\.\d+"
  register: ip
  with_items: "{{ contenedores.stdout_lines }}"

- name: Genrando archivo con direccion IP de los esclavos
  copy:
    content: "{% for host in groups.workers %}{% set first_loop = loop.index %}{% for result in hostvars[host]['ip']['results'] %}{% if first_loop == 1 and loop.index == 1 %}{{result.stdout}}{% else %},{{result.stdout}}{% endif %}{% endfor %}{% endfor %}"
    dest: /home/linux/performance/ipAddressSlaves
