- name: Crear carpeta performance
  file: path=/home/linux/performance/utils state=directory owner=linux group=linux

- name: Copiar archivo para obtener ip de los esclavos
  copy: src=getSlavesIp.sh dest=/home/linux/performance/utils owner=linux group=linux
