- name: Instala Docker
  hosts: servers
  become: true
  roles:
    - docker-install

- name: Inicia Swarm
  hosts: manager
  become: true
  roles:
    - docker-swarm-init

- name: Agrega Workers al Swarm
  hosts: workers
  become: true
  roles:
    - docker-swarm-join

- name: Inicia Stack de Jmeter
  hosts: manager
  become: true
  roles:
    - docker-stack-deploy

- name: Scripts de utilidad para el manager
  hosts: manager
  become: true
  roles:
    - scripts-utils-manager

- name: Scripts de utilidad para los workers
  hosts: workers
  become: true
  roles:
    - scripts-utils-workers

- name: Configuracion Inicial de Grafana
  hosts: manager
  become: true
  roles:
    - grafana-users
    - grafana-datasource
